name: Go Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          # Exclude arm64 on Windows since GitHub doesn't provide arm64 Windows runners
          - os: windows-latest
            arch: arm64
          # Exclude unsupported combinations (older Ubuntu doesn't support arm64)
          - os: ubuntu-22.04
            arch: arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up QEMU (Linux ARM64)
      if: matrix.arch == 'arm64' && runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3

    - name: Build
      run: go build -v ./...
      env:
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0  # Disable CGO for static binaries

    - name: Test
      run: go test -v ./...
      env:
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
